"""Initial migration

Revision ID: 344e42f637c9
Revises: 
Create Date: 2024-09-13 11:21:35.468960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '344e42f637c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('san_pham')
    op.drop_table('dh_sp')
    op.drop_table('treatment')
    op.drop_table('don_hang_chi_tiet')
    op.drop_table('don_hang')
    op.drop_table('customer_skin')
    op.drop_table('mask')
    op.drop_table('spa_card')
    op.drop_index('username', table_name='user_account')
    op.drop_table('user_account')
    op.drop_table('kh_dh')
    op.drop_table('spa_booking')
    op.drop_table('card_staff')
    op.drop_table('skin_type')
    op.drop_table('product_skin')
    op.drop_table('task_customer')
    op.drop_index('id', table_name='khach_hang')
    op.drop_table('khach_hang')
    op.drop_table('task')
    op.drop_table('card_treatment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_treatment',
    sa.Column('card_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('treatment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('time_used', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['spa_card.id'], name='card_treatment_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name='card_treatment_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'treatment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('task',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('khach_hang',
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('ten_khach_hang', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('so_dien_thoai', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('khu_vuc', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('dia_chi', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('nhom_khach_hang', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ngay_sinh', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('skin_property', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('payment_ability', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('last_buying_day', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('point', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('day_without_buying', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('id', 'khach_hang', ['id'], unique=True)
    op.create_table('task_customer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deadline', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('finished', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('outdated', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('extra_description', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['khach_hang.id'], name='task_customer_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['user_account.id'], name='task_customer_ibfk_3', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], name='task_customer_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('product_skin',
    sa.Column('skin_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['san_pham.id'], name='product_skin_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skin_type_id'], ['skin_type.id'], name='product_skin_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skin_type_id', 'product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('skin_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type_name', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('card_staff',
    sa.Column('card_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['spa_card.id'], name='card_staff_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['user_account.id'], name='card_staff_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'staff_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('spa_booking',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('card_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('treatment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mask_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('note', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('customer_demand', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['spa_card.id'], name='spa_booking_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mask_id'], ['mask.id'], name='spa_booking_ibfk_4', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['user_account.id'], name='spa_booking_ibfk_3', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['treatment_id'], ['treatment.id'], name='spa_booking_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('kh_dh',
    sa.Column('khach_hang_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('don_hang_id', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], name='kh_dh_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['khach_hang_id'], ['khach_hang.id'], name='kh_dh_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('khach_hang_id', 'don_hang_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_account',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('user_password', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('user_role', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user_account', ['username'], unique=True)
    op.create_table('spa_card',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('total_price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('paid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('debt', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', mysql.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['khach_hang.id'], name='spa_card_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('mask',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mask_name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('customer_skin',
    sa.Column('skin_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['khach_hang.id'], name='customer_skin_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skin_type_id'], ['skin_type.id'], name='customer_skin_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('skin_type_id', 'customer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('don_hang',
    sa.Column('id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('document_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('finish_date', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('branch', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('selling_source', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('staff', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('customer_name', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('product_amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('customer_payment', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('note', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('don_hang_chi_tiet',
    sa.Column('stt', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('don_hang_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('ten_san_pham', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('so_luong', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('stt'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('treatment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('duration', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dh_sp',
    sa.Column('don_hang_id', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('san_pham_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('so_luong', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['don_hang_id'], ['don_hang.id'], name='dh_sp_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['san_pham_id'], ['san_pham.id'], name='dh_sp_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('don_hang_id', 'san_pham_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('san_pham',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ten_san_pham', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('listed_price', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mo_ta', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('anh', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('ma_SKU', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('khoi_luong', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('outdate_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
