"""Delete column count_id in Khach_hang

Revision ID: fcb1bdcddec6
Revises: 
Create Date: 2024-08-02 12:00:33.666948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcb1bdcddec6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_id_count')
    with op.batch_alter_table('khach_hang', schema=None) as batch_op:
        batch_op.drop_index('count_id_UNIQUE')
        batch_op.drop_column('count_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('khach_hang', schema=None) as batch_op:
        batch_op.add_column(sa.Column('count_id', mysql.INTEGER(), autoincrement=True, nullable=False))
        batch_op.create_index('count_id_UNIQUE', ['count_id'], unique=True)

    op.create_table('customer_id_count',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
